config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to=>"root#top"


  get "top"=>"root#top", as: "top"
  get "about"=>"root#about", as: "about"
  get "contact"=>"root#contact", as:"contact"
  # 例外的にrootの中に定義　名前の付け方も例外的、規則に沿ってない
  get "root/blogs/:id"=>"root#root_show", as:"root_post_blog"
  get "root/blogs"=>"root#root_index", as:"root_post_blogs"
  #以上ふたつ
  resources :post_blogs, :except=>[:show, :index]
  resources :inquiries ,:except=>[:new, :edit, :update]
  resources :post_informations
  resources :post_images, :except=>[:index]
  resources :users
  resources :post_files

  # get "post_files/:id/download"=> "post_files#download", as:"post_file_download"
  
# 自分で定義
  # get "users/edit/all"=>"users#edit_all", as:"edit_all_users"
  # patch "users/update/all"=>"users#update_all", as:"update_all_users"

  get "numbers"=>"users#numbers", as:"numbers"
  resources :post_applications do
  	resources :post_application_responses, :except=>[:new]
  end
end

app/models/post_information.rb
class PostInformation < ApplicationRecord
	belongs_to :user

	attachment :image
	validates :title, presence:true
end

app/controllers/post_informations_controller.rb
class PostInformationsController < ApplicationController
	def new
		if judge(current_user)>=2
			@post_information=PostInformation.new
		else
			redirect_to post_informations_path
		end
	end
	def edit
		if judge(current_user)>=2
			@post_information=PostInformation.find(params[:id])
		else
			redirect_to post_informations_path
		end
	end
	def create
		@post_information=PostInformation.new(post_information_params)
		@post_information.user_id=current_user.id
		if @post_information.save
			redirect_to post_informations_path
		else
			render :new
		end
	end

	def index
		@post_informations=PostInformation.all
	end

	def show
		@post_information=PostInformation.find(params[:id])
	end

	def destroy
		@post_information=PostInformation.find(params[:id])
		# 権限を追記
		if judge(current_user)>=2
			@post_information.destroy
			redirect_to post_informations_path
		else
			redirect_to post_informations_path
		end
	end

	private
		def post_information_params
			params.require(:post_information).permit(:title, :comment, :place, :date, :image)
		end

end

app/helpers/post_informations_helper.rb
module PostInformationsHelper
end

app/views/post_informations/edit.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6  post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>Edit Information</span>
              </h3>
            </div>

            <%= form_for(@post_information) do |f| %>
              <% if @post_information.errors.any? %>
                <div id="error_explanation">
                  <ul class="alert alert-danger" role="alert">
                  <% @post_information.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Place</label>
                    <%= f.text_field :place, class:"form-control", placeholder:"Place" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Date</label>
                    <%= f.datetime_select :date, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_field :title, class:"form-control", rows:"3", placeholder:"Title" %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, class:"form-control", rows:"3", placeholder:"Comment" %>
                </div>
              </div>
              <%= f.submit "Edit", class:"btn btn-lg btn-block btn-base-1 mt-20 btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- 

<%=form_for(@post_information, url:post_informations_path) do |f| %>
	<% if @post_information.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @post_information.errors.full_messages.each do |message| %>
					<li><%=message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<div>
<h1>Add Information</h1>
</div>
	<div>
		<label>title</label>
		<%=f.text_field :title %>
	</div>
	<div>
		<label>comment</label>
		<%=f.text_area :comment %>
	</div>
	<div>
		<label>place</label>
		<%=f.text_field :place %>
	</div>
	<div>
		<label>date</label>
		<%=f.datetime_select :date %>
	</div>
	<div>
		<label>image</label>
		<%=f.attachment_field :image %>
	</div>
	<%=f.submit "Post" %>
<% end %> -->

app/views/post_informations/index.html.erb

<div class="container">
	<div class="row">
		<div class="col-lg-10 col-offset-2">
			<div class="page-header">
				<h1>Informations</h1>
			</div>
			<table class="table table-hover">
				<thead>
					<tr class="info">
						<th>Title</th>
						<th>Place</th>
						<th>Date</th>
						<% if judge(current_user)>=2 %>
							<th colspan="2"></th>
						<% end %>
					</tr>
				</thead>
				<tbody>
					<% @post_informations.each do |post_information| %>
						<tr>
							<th><%=link_to post_information.title, post_information_path(post_information) %></th>
							<th><%=post_information.place %></th>
							<th><%=post_information.date %></th>
							<% if judge(current_user)>=2 %>
								<th><%=link_to "delete", post_information_path(post_information), method: :delete, data: {confirm: "Are you sure?"}, :class=>"btn btn-danger btn-sm" %></th>
								<th><%=link_to "edit", edit_post_information_path(post_information), :class=>"btn btn-warning btn-sm" %>
								</th>
							<% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/post_informations/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6  post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>Add Information</span>
              </h3>
            </div>

            <%= form_for(@post_information, url: post_informations_path) do |f| %>
              <% if @post_information.errors.any? %>
                <div id="error_explanation">
                  <ul class="alert alert-danger" role="alert">
                  <% @post_information.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.attachment_field :image %>
                </div>
              </div>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Place</label>
                    <%= f.text_field :place, class:"form-control", placeholder:"Place" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Date</label>
                    <%= f.datetime_select :date, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_field :title, class:"form-control", rows:"3", placeholder:"Title" %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, class:"form-control", rows:"3", placeholder:"Comment" %>
                </div>
              </div>
              <%= f.submit "Add", class:"btn btn-lg btn-block btn-base-1 mt-20 btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<!-- 

<%=form_for(@post_information, url:post_informations_path) do |f| %>
	<% if @post_information.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @post_information.errors.full_messages.each do |message| %>
					<li><%=message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<div>
<h1>Add Information</h1>
</div>
	<div>
		<label>title</label>
		<%=f.text_field :title %>
	</div>
	<div>
		<label>comment</label>
		<%=f.text_area :comment %>
	</div>
	<div>
		<label>place</label>
		<%=f.text_field :place %>
	</div>
	<div>
		<label>date</label>
		<%=f.datetime_select :date %>
	</div>
	<div>
		<label>image</label>
		<%=f.attachment_field :image %>
	</div>
	<%=f.submit "Post" %>
<% end %> -->

app/views/post_informations/show.html.erb

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<div class="page-header">
				<h1>Information Detail</h1>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>Title:  <%=@post_information.title %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Place:  <%=@post_information.place %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Date:  <%=@post_information.date %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Comment:  <%=@post_information.comment %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th><%= attachment_image_tag @post_information, :image, :fill, 600, 600, format: 'jpeg', fallback: "no_image.jpg", :size=>"600×600" %></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>
