config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to=>"root#top"


  get "top"=>"root#top", as: "top"
  get "about"=>"root#about", as: "about"
  get "contact"=>"root#contact", as:"contact"
  # 例外的にrootの中に定義　名前の付け方も例外的、規則に沿ってない
  get "root/blogs/:id"=>"root#root_show", as:"root_post_blog"
  get "root/blogs"=>"root#root_index", as:"root_post_blogs"
  #以上ふたつ
  resources :post_blogs, :except=>[:show, :index]
  resources :inquiries ,:except=>[:new, :edit, :update]
  resources :post_informations
  resources :post_images, :except=>[:index]
  resources :users
  resources :post_files

  # get "post_files/:id/download"=> "post_files#download", as:"post_file_download"
  
# 自分で定義
  # get "users/edit/all"=>"users#edit_all", as:"edit_all_users"
  # patch "users/update/all"=>"users#update_all", as:"update_all_users"

  get "numbers"=>"users#numbers", as:"numbers"
  resources :post_applications do
  	resources :post_application_responses, :except=>[:new]
  end
end

app/models/post_application.rb
class PostApplication < ApplicationRecord
	belongs_to :user
	has_many :post_application_responses, dependent: :destroy
	validates :title, :place, :date, :deadline, presence: true

	def responded_by?(user)
		post_application_responses.where(user_id: user.id).exists?
	end
end

app/controllers/post_applications_controller.rb
class PostApplicationsController < ApplicationController
	def new
		if judge(current_user)>=3
			@post_application=PostApplication.new
		else
			redirect_to post_informations_path
		end
	end

	def create
		@post_application=PostApplication.new(post_application_params)
		@post_application.user_id=current_user.id
		if @post_application.save
				redirect_to post_applications_path
		else
			render :new
		end
	end

# response new/editを兼ねる
	def show
		@post_application=PostApplication.find(params[:id])
		@post_application_responses=PostApplicationResponse.where(post_application_id: @post_application.id)
		# if @post_application.responded_by?(current_user)
		#    @post_application_response=current_user.post_application_responses.find_by(post_application_id: @post_application.id)
		# else
		if @post_application.responded_by?(current_user)
			@post_application_response=current_user.post_application_responses.find_by(post_application_id: @post_application.id)
			# @post_application_response=PostApplicationResponse.find_by(post_application_id: @post_application.id)
		else
			@post_application_response=PostApplicationResponse.new
		end
		# end
		@users=User.all
	end

	def index
		@post_applications=PostApplication.all
	end

	def edit
		if judge(current_user)>=3
			@post_application=PostApplication.find(params[:id])
		else
			redirect_to post_applications_path
		end
	end

	def update
		@post_application=PostApplication.find(params[:id])
		if @post_application.update(post_application_params)
			redirect_to post_application_path(@post_application)
		else
			render :edit
		end
	end

	def destroy
		@post_application=PostApplication.find(params[:id])
		if judge(current_user)>=3
			@post_application.destroy
			redirect_to post_applications_path
		else
			redirect_to post_applications_path
		end
	end

	private
		def post_application_params
			 params.require(:post_application).permit(:title, :comment, :place, :date, :deadline, :target_grade, :target_home, :target_section)
		end
end

app/helpers/post_applications_helper.rb
module PostApplicationsHelper
end

app/views/post_applications/edit.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6  post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>Edit Application</span>
              </h3>
            </div>

            <%= form_for(@post_application) do |f| %>
              <% if @post_application.errors.any? %>
                <div id="error_explanation">
                  <ul class="alert alert-danger" role="alert">
                  <% @post_application.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Target</label>
                    <%=f.label :Grade %><br/>
                    <%= f.select :target_grade,[["All","All"],["Freshmen","1"],["Sophomore","2"],["Junior","3"],["Senior","4"]]%><br/>
                     <%=f.label :Section %><br/>
                    <%= f.select :target_section,[["All","All"],["Discussion","Discussion"],["Debate","Debate"],["Speech","Speech"],["Drama","Drama"]]%><br/>
                      <%=f.label :Home %><br/>
                    <%= f.select :target_home,[["All","All"],["Aoyama","Aoyama"],["Mita","Mita"],["Yokohama","Yokohama"]]%><br/>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Place</label>
                    <%= f.text_field :place, class:"form-control", placeholder:"Place" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Date</label>
                    <%= f.datetime_select :date, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Deadline</label>
                    <%= f.datetime_select :deadline, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_field :title, class:"form-control", rows:"3", placeholder:"Title" %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, class:"form-control", rows:"3", placeholder:"Comment" %>
                </div>
              </div>
              <%= f.submit "Edit", class:"btn btn-lg btn-block btn-base-1 mt-20 btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>













<!-- 


<%=form_for(@post_application, url:post_applications_path) do |f| %>
	<% if @post_application.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @post_application.errors.full_messages.each do |message| %>
					<li><%=message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<div class="page-header">
	<h1>Add Application</h1>
</div>
	<div>
		<div>
			<label>title</label>
			<%=f.text_field :title %>
		</div>
		<div>
			<label>comment</label>
			<%=f.text_area :comment %>
		</div>
		<div>
			<label>place</label>
			<%=f.text_field :place %>
		</div>
		<div>
			<label>date</label>
			<%=f.datetime_select :date %>
		</div>
		<div>
			<label>deadline</label>
			<%=f.datetime_select :deadline %>
		</div>
	<%=f.submit "Post", :class=>"btn btn-sm btn-info" %>
	</div>
<% end %> -->

app/views/post_applications/index.html.erb

<div class="container">
	<div class="row">
		<div class="col-lg-10 col-offset-2">
			<div class="page-header">
				<h1>Applications</h1>
			</div>
			<table class="table table-hover">
				<thead>
					<tr class="info">
						<th>Target(Grade_Home_Section)</th>
						<th>Title</th>
						<th>Place</th>
						<th>Date</th>
						<th>Deadline</th>
						<th>Reply?</th>
						<th colspan="2"></th>
					</tr>
				</thead>
				<tbody>
					<% @post_applications.each do |post_application| %>
					<!-- アプリケ対象者または委員なら表示 -->
						<% if aimed?(post_application,current_user) || judge(current_user)>=3 %>
							<tr>
								<th class="btn btn-success btn-block"><%=post_application.target_grade+"_"+post_application.target_home+"_"+post_application.target_section %></th>
								<th><%=link_to post_application.title, post_application_path(post_application) %></th>
								<th><%=post_application.place %></th>
								<th><%=post_application.date %></th>
								<th class="warning"><%=post_application.deadline %></th>
							<% if aimed?(post_application,current_user) %>
								<% if post_application.responded_by?(current_user) %>
									<th class="btn btn-xs btn-success">Done!</th>
								<% else %>
		  						    <th class="btn btn-xs btn-danger">Yet!</th>
								<% end %>
							<% else %>
							<!-- 委員として管理しているだけなら -->
									<th class="btn btn-xs btn-info">Unnecessary</th>
							<% end %>
								<% if judge(current_user)>=3 %>
									<th><%=link_to "Delete", post_application_path(post_application), method: :delete, data: {confirm: "Are you sure?"}, :class=>"btn btn-danger btn-sm" %></th>
									<th><%=link_to "Edit", edit_post_application_path(post_application), :class=>"btn btn-warning btn-sm" %>
								<% end %>
							</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>


app/views/post_applications/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6  post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>Add Application</span>
              </h3>
            </div>

            <%= form_for(@post_application, url: post_applications_path) do |f| %>
              <% if @post_application.errors.any? %>
                <div id="error_explanation">
                  <ul class="alert alert-danger" role="alert">
                  <% @post_application.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <br>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Target</label>
                    <%=f.label :Grade %><br/>
                    <%= f.select :target_grade,[["All","All"],["Freshmen","1"],["Sophomore","2"],["Junior","3"],["Senior","4"]]%><br/>
                     <%=f.label :Section %><br/>
                    <%= f.select :target_section,[["All","All"],["Discussion","Discussion"],["Debate","Debate"],["Speech","Speech"],["Drama","Drama"]]%><br/>
                      <%=f.label :Home %><br/>
                    <%= f.select :target_home,[["All","All"],["Aoyama","Aoyama"],["Mita","Mita"],["Yokohama","Yokohama"]]%><br/>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-6">
                  <div class="form-group has-icon">
                    <label class="control-label sr-only">Place</label>
                    <%= f.text_field :place, class:"form-control", placeholder:"Place" %>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Date</label>
                    <%= f.datetime_select :date, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-icon">
                    <label class="control-label">Deadline</label>
                    <%= f.datetime_select :deadline, class:"form-control"%>
                    <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                  </div>
                </div>
                <div class="col-sm-6">
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_field :title, class:"form-control", rows:"3", placeholder:"Title" %>
                </div>
              </div>
              <div class="row">
                <div class="col-sm-12">
                  <%= f.text_area :comment, class:"form-control", rows:"3", placeholder:"Comment" %>
                </div>
              </div>
              <%= f.submit "Add", class:"btn btn-lg btn-block btn-base-1 mt-20 btn-info" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>













<!-- 


<%=form_for(@post_application, url:post_applications_path) do |f| %>
	<% if @post_application.errors.any? %>
		<div id="error_explanation">
			<ul>
				<% @post_application.errors.full_messages.each do |message| %>
					<li><%=message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<div class="page-header">
	<h1>Add Application</h1>
</div>
	<div>
		<div>
			<label>title</label>
			<%=f.text_field :title %>
		</div>
		<div>
			<label>comment</label>
			<%=f.text_area :comment %>
		</div>
		<div>
			<label>place</label>
			<%=f.text_field :place %>
		</div>
		<div>
			<label>date</label>
			<%=f.datetime_select :date %>
		</div>
		<div>
			<label>deadline</label>
			<%=f.datetime_select :deadline %>
		</div>
	<%=f.submit "Post", :class=>"btn btn-sm btn-info" %>
	</div>
<% end %> -->

app/views/post_applications/show.html.erb

<!-- new＿post_application_post_application_response/ post_application_post_application_responsesを兼ねる-->
<%=form_for [@post_application, @post_application_response] do |f| %>
<div id="error_explanation">
		<% if @post_application_response.errors.any? %>
			<ul class="alert alert-danger" role="alert">
				<% @post_application_response.errors.full_messages.each do |message| %>
					<li><%=message %></li>
				<% end %>
			</ul>
		<% end %>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-6 ">
			<div class="page-header">
				<h1>Application Detail</h1>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th>Title:  <%=@post_application.title %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Place:  <%=@post_application.place %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Date:  <%=@post_application.date %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Deadline:  <%=@post_application.deadline %></th>
					</tr>
				</thead>
				<thead>
					<tr>
						<th>Comment: <%=@post_application.comment %>
					</tr>
				</thead>
			</table>
			<% if aimed?(@post_application,current_user) %>
			<table class="table">
				<tbody>
					<tr>
							<div class="page-header">
								<h1>Reply</h1>
							</div>
					</tr>
					<tr>
								<div class="field">
									<label>participate?</label>
									<%=f.select :participation, [["Yes","〇"],["Partially, Yes","△"],["No","✕"],["Not sure","?"]] %>
								</div>
					</tr>
					<tr>
								<div class="field">
									<p>For those who answered "Partially, Yes" above </p>
									<label>From when to when you can come</label>
										<%=f.text_field :caption %>
								</div>
					</tr>
					<tr>
								<div class="field">
									<p>For those who answered "No" above </p>
									<label>Reason why you cannot come</label>
									<%=f.select :reason, [["Academics","Academics"],["Part-time jobs","Part-time jobs"],["Ceremonial occasions","Ceremonial occasions"],["Disease","Disease"],["Previous engagement","Previous engagement"],["Others","Others"]], :include_blank => true %>
								</div>
					</tr>
			    	<tr>
								<% if @post_application.responded_by?(current_user) %>
									<%=f.submit "Update", :class=>"btn btn-info btn-block" %>
								<% else %>
									<%=f.submit "Respond", :class=>"btn btn-info btn-block" %>
								<% end %>
				    </tr>
				</body>
			</table>
			<% end %>
		</div>
		<div class="col-md-3">
			<div class="page-header">
				<h1>Response</h1>
			</div>
			<table class="table table-hover">
				<thead>
					<tr class="info">
						<th>Username</th>
						<th>Reply?</th>
						<th colspan="4"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
						<% if aimed?(@post_application,user) %>
						<tr>
							<th><%=link_to "#{user.firstname+" "+user.lastname}", user_path(user) %></th>
							<% if @post_application.responded_by?(user) %>
								<th class="btn btn-xs btn-success">Done!</th>
								<% @post_application_responses.each do |post_application_response| %>
									<% if post_application_response.user_id==user.id %>
										<th><%=post_application_response.participation %></th>
										<% if post_application_response.participation=="✕" %>
											<th><%= post_application_response.reason %></th>
										<% elsif post_application_response.participation=="△" %>
											<th><%=post_application_response.caption %></th>
										<% else %>
											<th>All Day</th>
										<% end %>
									<% end %>
								<% end %>
							<% else %>
								<th class="btn btn-xs btn-danger">Yet!</th>
							<% end %>
						</tr>
						<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<% end %>

