config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to=>"root#top"


  get "top"=>"root#top", as: "top"
  get "about"=>"root#about", as: "about"
  get "contact"=>"root#contact", as:"contact"
  # 例外的にrootの中に定義　名前の付け方も例外的、規則に沿ってない
  get "root/blogs/:id"=>"root#root_show", as:"root_post_blog"
  get "root/blogs"=>"root#root_index", as:"root_post_blogs"
  #以上ふたつ
  resources :post_blogs, :except=>[:show, :index]
  resources :inquiries ,:except=>[:new, :edit, :update]
  resources :post_informations
  resources :post_images, :except=>[:index]
  resources :users
  resources :post_files

  # get "post_files/:id/download"=> "post_files#download", as:"post_file_download"
  
# 自分で定義
  # get "users/edit/all"=>"users#edit_all", as:"edit_all_users"
  # patch "users/update/all"=>"users#update_all", as:"update_all_users"

  get "numbers"=>"users#numbers", as:"numbers"
  resources :post_applications do
  	resources :post_application_responses, :except=>[:new]
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

	def top
		# あたらしいものから
		@post_blogs=PostBlog.all.reverse_order
		if image_posted?
			@post_image=PostImage.last
		end
		@users=User.where(status: ["Regular", "Associate"])
	end

	def contact
		@inquiry=Inquiry.new
	end

	def about
	end
	# post_blog用
	def root_show
		@post_blog=PostBlog.find(params[:id])
		@post_blogs=PostBlog.all.reverse_order
	end

	def root_index
		@post_blogs=PostBlog.search(params[:search]).page(params[:page]).reverse_order
	end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/about.html.erb
<header id="header">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
						<span class="logo color-info">KESS</span>
					</div>
					<!-- /Logo -->

					<!-- Mobile toggle -->
					<button class="navbar-toggle">
						<span></span>
					</button>
					<!-- /Mobile toggle -->
				</div>

				<!-- Navigation -->
				<nav id="nav">
					<ul class="main-menu nav navbar-nav navbar-right">
						<li><%=link_to "Top", top_path %></li>
						<li><%=link_to "About", about_path %></li>
						<li><%=link_to "Blog", root_post_blogs_path %></li>
						<li><%=link_to "Contact", contact_path %></li>
					<% if user_signed_in? %>
						<li><%=link_to "Back", post_informations_path %></li>
					<% else %>
						<li><%=link_to "Sign up", new_user_registration_path %></li>
						<li><%=link_to "Log in", new_user_session_path %></li>
					<% end %>
					</ul>
				</nav>
				<!-- /Navigation -->

			</div>
		</header>
		<!-- /Header -->

		<!-- Hero-area -->
		<div class="hero-area section">
			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url(<%= asset_path 'main_image_default.jpg' %>)"></div>
			<!-- /Backgound Image -->

			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><%=link_to "Top", top_path %></li>
							<li>About</li>
						</ul>
						<h1 class="white-text">Learn more about us</h1>

					</div>
				</div>
			</div>

		</div>
		<!-- /Hero-area -->

		<!-- Contact -->
		<div id="contact" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">
					<!-- contact form -->
					<div class="col-md-6">
						<p>
							慶應義塾大学英語會（Keio English Speaking Society）<br>
…通称「K.E.S.S.（けす）」創立126年の慶應公認団体<br>

日本最大規模のESSを誇る。<br>

「英語によるCommunication能力の向上」を目標として掲げ、英語力の向上だけでなく、論理的に意見を創造するための活動を行っている。そのため就職活動ではトップを走る将来が約束されている。

Debate・Discussion・Drama・SpeechのSectionに分かれ、幅広く、日々活動に励んでいる。
						</p>
					</div>
					<!-- /contact form -->

					<!-- contact information -->
					<div class="col-md-5 col-md-offset-1">
						<h4>Contact Information</h4>
						<ul class="contact-details">
							<li><i class="fas fa-envelope"></i>presskess@gmail.com</li>
							<li><i class="fas fa-phone"></i>122-547-223-45</li>
						</ul>

						<!-- contact map -->
					<!-- 	<div id="contact-map"></div> -->
						<!-- /contact map -->

					</div>
					<!-- contact information -->

				</div>
				<!-- /row -->

			</div>
			<!-- /container -->

		</div>
		<!-- /Contact -->

		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
						<!-- 	<a class="logo" href="index.html">
								<img src="./img/logo.png" alt="logo">
							</a> -->
							<span>Keio English Speaking Society</span>
						</div>
					</div>
					<!-- footer logo -->

					<!-- footer nav -->
					<div class="col-md-6">
						<ul class="footer-nav">
							<li><%=link_to "Top", top_path %></li>
							<li><%=link_to "About", about_path %></li>
							<li><%=link_to "Blog", root_post_blogs_path %></li>
							<li><%=link_to "Contact", contact_path %></li>
						</ul>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<!-- <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li> -->
							<li><a href="https://twitter.com/2019kess" class="twitter"><i class="fab fa-twitter"></i></a></li>
							<!-- <li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li> -->
							<li><a href="https://www.instagram.com/2019kess/" class="instagram"><i class="fab fa-instagram"></i></a></li>
							<!-- <li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
							<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li> -->
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
							<span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></span>
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->

		<!-- jQuery Plugins -->
	<!-- 	<%= javascript_include_tag 'jquery.min.js' %> -->
		<%= javascript_include_tag 'bootstrap.min.js' %>
	<!-- 	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script> -->
		<%= javascript_include_tag 'main.js' %>

app/views/root/contact.html.erb
<header id="header">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
						<span class="logo color-info">KESS</span>
					</div>
					<!-- /Logo -->

					<!-- Mobile toggle -->
					<button class="navbar-toggle">
						<span></span>
					</button>
					<!-- /Mobile toggle -->
				</div>

				<!-- Navigation -->
				<nav id="nav">
					<ul class="main-menu nav navbar-nav navbar-right">
						<li><%=link_to "Top", top_path %></li>
						<li><%=link_to "About", about_path %></li>
						<li><%=link_to "Blog", root_post_blogs_path %></li>
						<li><%=link_to "Contact", contact_path %></li>
					<% if user_signed_in? %>
						<li><%=link_to "Back", post_informations_path %></li>
					<% else %>
						<li><%=link_to "Sign up", new_user_registration_path %></li>
						<li><%=link_to "Log in", new_user_session_path %></li>
					<% end %>
					</ul>
				</nav>
				<!-- /Navigation -->

			</div>
		</header>
		<!-- /Header -->

		<!-- Hero-area -->
		<div class="hero-area section">
			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url(<%= asset_path 'main_image_default.jpg' %>)"></div>
			<!-- /Backgound Image -->

			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><%=link_to "Top", top_path %></li>
							<li>Contact</li>
						</ul>
						<h1 class="white-text">Get In Touch</h1>

					</div>
				</div>
			</div>

		</div>
		<!-- /Hero-area -->

		<!-- Contact -->
		<div id="contact" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">
					<% if @inquiry.errors.any? %>
	                	<div id="error_explanation">
		               	   <ul class="alert alert-danger" role="alert">
		                	  <% @inquiry.errors.full_messages.each do |message| %>
		               	     <li><%= message %></li>
		               	      <% end %>
		                  </ul>
	            	    </div>
            	    <% end %>
            	    <% if flash.now[:contact] %>
            	    	<div id="error_explanation">
		               	   <ul class="alert alert-success" role="alert">
		               	     <li><%= flash.now[:contact] %></li>
		                  </ul>
	            	    </div>
            	    <% end %>

					<!-- contact form -->
					<div class="col-md-6">
						<div class="contact-form">
							<h4>Send A Message</h4>
							<%=form_for @inquiry, url: inquiries_path do |f| %>
							<form>
								<%= f.text_field :name, class:"input form-control", placeholder:"Enter your Name" %>
								<%= f.text_field :email, class:"input form-control", placeholder:"Enter your Email", autocomplete: "email"  %>
								<%=f.text_area :content, class:"input form-control", placeholder:"Enter your Message" %>
								<%=f.submit "Send", class:"main-button icon-button pull-right" %>
							</form>
							<% end %>
						</div>
					</div>
					<!-- /contact form -->

					<!-- contact information -->
					<div class="col-md-5 col-md-offset-1">
						<h4>Contact Information</h4>
						<ul class="contact-details">
							<li><i class="fas fa-envelope"></i>presskess@gmail.com</li>
							<li><i class="fas fa-phone"></i>122-547-223-45</li>
						</ul>

						<!-- contact map -->
					<!-- 	<div id="contact-map"></div> -->
						<!-- /contact map -->

					</div>
					<!-- contact information -->

				</div>
				<!-- /row -->

			</div>
			<!-- /container -->

		</div>
		<!-- /Contact -->

		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
						<!-- 	<a class="logo" href="index.html">
								<img src="./img/logo.png" alt="logo">
							</a> -->
							<span>Keio English Speaking Society</span>
						</div>
					</div>
					<!-- footer logo -->

					<!-- footer nav -->
					<div class="col-md-6">
						<ul class="footer-nav">
							<li><%=link_to "Top", top_path %></li>
							<li><%=link_to "About", about_path %></li>
							<li><%=link_to "Blog", root_post_blogs_path %></li>
							<li><%=link_to "Contact", contact_path %></li>
						</ul>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<!-- <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li> -->
							<li><a href="https://twitter.com/2019kess" class="twitter"><i class="fab fa-twitter"></i></a></li>
							<!-- <li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li> -->
							<li><a href="https://www.instagram.com/2019kess/" class="instagram"><i class="fab fa-instagram"></i></a></li>
							<!-- <li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
							<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li> -->
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
							<span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></span>
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->

		<!-- jQuery Plugins -->
	<!-- 	<%= javascript_include_tag 'jquery.min.js' %> -->
		<%= javascript_include_tag 'bootstrap.min.js' %>
	<!-- 	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script> -->
		<%= javascript_include_tag 'main.js' %>

app/views/root/root_index.html.erb
<!--post_blog_index  -->
<!-- Header -->
		<header id="header">
			<div class="container">

				<div class="navbar-header">
					<!-- Logo -->
					<div class="navbar-brand">
						<span class="logo color-info">KESS</span>
					</div>
					<!-- /Logo -->

					<!-- Mobile toggle -->
					<button class="navbar-toggle">
						<span></span>
					</button>
					<!-- /Mobile toggle -->
				</div>

				<!-- Navigation -->
				<nav id="nav">
					<ul class="main-menu nav navbar-nav navbar-right">
						<li><%=link_to "Top", top_path %></li>
						<li><%=link_to "About", about_path %></li>
						<li><%=link_to "Blog", root_post_blogs_path %></li>
						<li><%=link_to "Contact", contact_path %></li>
					<% if user_signed_in? %>
						<li><%=link_to "Back", post_informations_path %></li>
					<% else %>
						<li><%=link_to "Sign up", new_user_registration_path %></li>
						<li><%=link_to "Log in", new_user_session_path %></li>
					<% end %>
					</ul>
				</nav>
				<!-- /Navigation -->

			</div>
		</header>
		<!-- /Header -->

		<!-- Hero-area -->
		<div class="hero-area section">

			<!-- Backgound Image -->
			<div class="bg-image bg-parallax overlay" style="background-image:url(<%= asset_path 'main_image_default.jpg' %>)"></div>
			<!-- /Backgound Image -->

			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1 text-center">
						<ul class="hero-area-tree">
							<li><%=link_to "Top", top_path %></li>
							<li>Blog</li>
						</ul>
						<h1 class="white-text">Blog Page</h1>

					</div>
				</div>
			</div>

		</div>
		<!-- /Hero-area -->

		<!-- Blog -->
		<div id="blog" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- main blog -->
					<div id="main" class="col-md-9">

						<!-- row -->
						<div class="row">

							<!-- single blog -->
						<% @post_blogs.each do |post_blog| %>
							<div class="col-md-6">
								<div class="single-blog">
									<div class="blog-img">
										<%=link_to (attachment_image_tag post_blog,:image, :fill, 800,500), root_post_blog_path(post_blog) %>
									</div>
									<h4><%=link_to "#{post_blog.title}", root_post_blog_path(post_blog) %></h4>
									<div class="blog-meta">
										<span class="blog-meta-author">By: <%=post_blog.user.firstname+" "+post_blog.user.lastname %></span>
										<div class="pull-right">
											<span><%=post_blog.created_at %></span>
										<% if user_signed_in? %>
											<% if judge(current_user)>=3 %>
											<span ><%=link_to "Delete", post_blog_path(post_blog), method: :delete, data: {confirm: "Are you sure? This action can never be undone."}, :class=>"btn btn-danger btn-sm" %></span>
											<span ><%=link_to "Edit", edit_post_blog_path(post_blog), :class=>"btn btn-warning btn-sm" %></span>
											<% end %>
										<% end %>
										</div>
									</div>
								</div>
							</div>
						<% end %>
							<!-- /single blog -->

						</div>
						<!-- /row -->

						<!-- row -->
						<div class="row">

							<!-- pagination -->
							<div class="col-md-12">
								<div class="post-pagination">
									<%= paginate @post_blogs, class:"paginate" %>
									<!-- <a href="#" class="pagination-back pull-left">Back</a>
									<ul class="pages">
										<li class="active">1</li>
										<li><a href="#">2</a></li>
										<li><a href="#">3</a></li>
										<li><a href="#">4</a></li>
									</ul>
									<a href="#" class="pagination-next pull-right">Next</a> -->
								</div>
							</div>
							<!-- pagination -->

						</div>
						<!-- /row -->
					</div>
					<!-- /main blog -->

					<!-- aside blog -->
					<div id="aside" class="col-md-3">

						<!-- search widget -->
						<div class="widget search-widget">
							<form>
							<%=form_tag(root_post_blogs_path,:method=>"get") do %>
							<%=text_field_tag :search, "#{params[:search]}", :class=>"input" %>
							<%=submit_tag "Search", :name=>nil, :class=>"btn btn-info" %>
							<% end %>
							</form>
							<!-- <form>
								<input class="input" type="text" name="search">
								<button><i class="fa fa-search"></i></button>
							</form> -->
						</div>
						<!-- /search widget -->

						<!-- category widget -->
						<!-- <div class="widget category-widget">
							<h3>Categories</h3>
							<a class="category" href="#">Web <span>12</span></a>
							<a class="category" href="#">Css <span>5</span></a>
							<a class="category" href="#">Wordpress <span>24</span></a>
							<a class="category" href="#">Html <span>78</span></a>
							<a class="category" href="#">Business <span>36</span></a>
						</div> -->
						<!-- /category widget -->

						<!-- posts widget -->
						<div class="widget posts-widget">
							<h3>Recents Posts</h3>

						<% count=0 %>
						<% @post_blogs.each do |post_blog| %>
							<% if count==3 %>
								<% break %>
							<% end %>
							<!-- single posts -->
							<div class="single-post">
								<%=link_to (attachment_image_tag post_blog, :image, :fill, 70,50), root_post_blog_path(post_blog) %>
							<!-- 	<a class="single-post-img" href="blog-post.html">
									<img src="./img/post01.jpg" alt="">
								</a> -->
								<%=link_to "#{post_blog.title}",root_post_blog_path(post_blog) %>
								<p><small>By : <%=post_blog.user.firstname+" "+post_blog.user.lastname %> <%=post_blog.created_at %></small></p>
							</div>
						<% count+=1 %>
						<% end %>
							<!-- /single posts -->

						</div>
						<!-- /posts widget -->

						<!-- tags widget -->
					<!-- 	<div class="widget tags-widget">
							<h3>Tags</h3>
							<a class="tag" href="#">Web</a>
							<a class="tag" href="#">Photography</a>
							<a class="tag" href="#">Css</a>
							<a class="tag" href="#">Responsive</a>
							<a class="tag" href="#">Wordpress</a>
							<a class="tag" href="#">Html</a>
							<a class="tag" href="#">Website</a>
							<a class="tag" href="#">Business</a>
						</div> -->
						<!-- /tags widget -->

					</div>
					<!-- /aside blog -->

				</div>
				<!-- row -->

			</div>
			<!-- container -->

		</div>
		<!-- /Blog -->

		<!-- Footer -->
		<footer id="footer" class="section">

			<!-- container -->
			<div class="container">

				<!-- row -->
				<div class="row">

					<!-- footer logo -->
					<div class="col-md-6">
						<div class="footer-logo">
						<!-- 	<a class="logo" href="index.html">
								<img src="./img/logo.png" alt="logo">
							</a> -->
							<span>Keio English Speaking Society</span>
						</div>
					</div>
					<!-- footer logo -->

					<!-- footer nav -->
					<div class="col-md-6">
						<ul class="footer-nav">
							<li><%=link_to "Top", top_path %></li>
							<li><%=link_to "About", about_path %></li>
							<li><%=link_to "Blog", root_post_blogs_path %></li>
							<li><%=link_to "Contact", contact_path %></li>
						</ul>
					</div>
					<!-- /footer nav -->

				</div>
				<!-- /row -->

				<!-- row -->
				<div id="bottom-footer" class="row">

					<!-- social -->
					<div class="col-md-4 col-md-push-8">
						<ul class="footer-social">
							<!-- <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li> -->
							<li><a href="https://twitter.com/2019kess" class="twitter"><i class="fab fa-twitter"></i></a></li>
							<!-- <li><a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a></li> -->
							<li><a href="https://www.instagram.com/2019kess/" class="instagram"><i class="fab fa-instagram"></i></a></li>
							<!-- <li><a href="#" class="youtube"><i class="fa fa-youtube"></i></a></li>
							<li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li> -->
						</ul>
					</div>
					<!-- /social -->

					<!-- copyright -->
					<div class="col-md-8 col-md-pull-4">
						<div class="footer-copyright">
							<span>&copy; Copyright 2018. All Rights Reserved. | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com">Colorlib</a></span>
						</div>
					</div>
					<!-- /copyright -->

				</div>
				<!-- row -->

			</div>
			<!-- /container -->

		</footer>
		<!-- /Footer -->

		<!-- preloader -->
		<div id='preloader'><div class='preloader'></div></div>
		<!-- /preloader -->


		<!-- jQuery Plugins -->
	<!-- 	<%= javascript_include_tag 'jquery.min.js' %> -->
		<%= javascript_include_tag 'bootstrap.min.js' %>
		<%= javascript_include_tag 'main.js' %>