config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to=>"root#top"


  get "top"=>"root#top", as: "top"
  get "about"=>"root#about", as: "about"
  get "contact"=>"root#contact", as:"contact"
  # 例外的にrootの中に定義　名前の付け方も例外的、規則に沿ってない
  get "root/blogs/:id"=>"root#root_show", as:"root_post_blog"
  get "root/blogs"=>"root#root_index", as:"root_post_blogs"
  #以上ふたつ
  resources :post_blogs, :except=>[:show, :index]
  resources :inquiries ,:except=>[:new, :edit, :update]
  resources :post_informations
  resources :post_images, :except=>[:index]
  resources :users
  resources :post_files

  # get "post_files/:id/download"=> "post_files#download", as:"post_file_download"
  
# 自分で定義
  # get "users/edit/all"=>"users#edit_all", as:"edit_all_users"
  # patch "users/update/all"=>"users#update_all", as:"update_all_users"

  get "numbers"=>"users#numbers", as:"numbers"
  resources :post_applications do
  	resources :post_application_responses, :except=>[:new]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KESSWEB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <h2>KESS</h2>
        </nav>>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%=link_to "File", post_files_path %></li>
              <li><%=link_to "Member", users_path %></li>
              <li><%=link_to "Information", post_informations_path %></li>
              <li><%=link_to "Application", post_applications_path %></li>
              <li><%=link_to "My page", user_path(current_user) %></li>
              <li><%=link_to "Home", top_path %></li>
              <li><%=link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%=link_to "Top", top_path %></li>
              <li><%=link_to "About", about_path %></li>
              <li><%=link_to "Blog", root_post_blogs_path %></li>
              <li><%=link_to "Contact", contact_path %></li>
              <li><%=link_to "Sign up", new_user_registration_path %></li>
              <li><%=link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <% if user_signed_in? %>
      <main>
        <div class="container">
          <div class="row">
            <nav class="col-lg-2 sidebar" style=" background-color:#383838;">
              <div class="sidebar-sticky">
                <ul class="nav flex-column nav-sidebar">
                  <% if judge(current_user)<=1 %>
                    <li class="nav-item">No option is available</li>
                  <% end %>
                  <% if judge(current_user)>=2 %>
                    <li class="nav-item"><%=link_to "Post Infomation", new_post_information_path %></li>
                  <% end %>
                  <% if judge(current_user)>=3 %>
                    <li class="nav-item"><%=link_to "Post Application", new_post_application_path %></li>
                    <li class="nav-item"><%=link_to "Post File", new_post_file_path %></li>
                    <li class="nav-item"><%=link_to "Post Blog", new_post_blog_path %></li>
                    <% if image_posted? %>
                       <li class="nav-item"><%=link_to "Change Image", edit_post_image_path(image_last_id) %></li>
                    <% else %>
                       <li class="nav-item"><%=link_to "Post Image", new_post_image_path %></li>
                    <% end %>
                    <li class="nav-item"><%=link_to "Number", numbers_path %></li>
                    <li class="nav-item"><%=link_to "Inquiry", inquiries_path %></li>
                  <% end %>
                  <!-- 管理者ページへのリンク -->
                  <% if current_user.try(:admin?) %>
                     <li class="nav-item"><%=link_to "Administration","/admin" %>
                  <% end %>
                </ul>
              </div>
            </nav>
            <div class="main col-lg-10">
             <%= yield %>
            </div>
          </div>
        </div>
      </main>
    <% else %>
      <main>
        <%=yield %>
      </main>
    <% end %>

    <footer class="footer style-2 footer_style">
      <div class="container">
        <div class="row">
          <p class="footer_text">ⒸAll rights reserved by Keio English Speaking Society</p>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/layouts/root.html.erb
<!DOCTYPE html>
<html lang="zxx">
  <head>
    <!-- top/aboutテンプレ用 -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
       <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->


      <!-- Google font -->

      <link href="https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600" rel="stylesheet">
      <!-- <link rel="stylesheet" href="style.css"> -->
      <!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
      <%=javascript_include_tag 'google-map.js'%> -->

      <!-- Bootstrap -->
      <%= stylesheet_link_tag "template/bootstrap.min", :media => "all" %>
      <!-- Font Awesome Icon -->
      <%= stylesheet_link_tag "template/font-awesome.min", :media => "all" %>
      <!-- Custom stlylesheet -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
      <%= stylesheet_link_tag "template/style",:media=>"all" %>
      <%= javascript_include_tag 'jquery.min.js' %>
      <%= javascript_include_tag "main" %>


<!-- top/about テンプレ用終わり -->

    <title>KESSWEB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<!-- turbolinksのせいでjavascriptが動かずreloadしないとだめになるからオフに -->
  <body data-turbolinks="false">
    <%=yield %>
  </body>
</html>